name: Pull Requests tests

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Clone the Project
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests with coverage
        run: |
          pytest --cov=./ --cov-report=xml
  

